repos:
- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
    - id: isort
      args: [ --line-length=120 ]

- repo: https://github.com/ambv/black
  rev: 22.3.0
  hooks:
    - id: black
      args: [ --line-length=120 ]

- repo: https://github.com/pycqa/pylint
  rev: v2.12.2
  hooks:
    - id: pylint
